label BwA18:
    "There was a competition stage situated in the heart of the Christmas market." 
    "Arriving at the competition stage, we suddenly realised that the area was quite empty." 
    u "I think that we're too late." 
    a "Huh?" 
    "I suddenly noticed a sign posted on the stage." 
    "\'Gift Wrapping competition concluded early as all prizes have been distributed.\'" 
    a "Aww..." 
    a "The competition really sounded fun." 
    u "Not really." 
    "It actually, it sounds {i}really{/i} lame." 
    a "I'm actually great at gift wrapping." 
    u "That's the {i}real{/i} reason you find it fun, huh." 
    a "Of course. If I can't win, what's the point?" 
    u "How competitive." 
    a "Well... then, what should we do now?" 
    u "Dunno." 
    "I noticed an empty bench near the stage." 
    u "Why don't we sit there at the bench?" 
    a "Why? It's not like I sprained my ankle while walking in sandals." 
    u "Who wears sandals in this weather?" 
    u "Regardless, you watch too many shows; you're thinking too deeply." 
    a "Why?" 
    a "Anime is fun to watch!" 
    u "Hehe." 
    a "What does that \'Hehe\' mean?" 
    a "Are you judging me?" 
    u "No, of course not. I, too, watch anime occasionally." 
    a "Then you have no grounds to judge me." 
    u "Didn't I just say that I wasn't judging you?" 
    a "Oh, right." 
    "The conversation up and died right there." 
    "How awkward..." 
    jump BwA19 
label BwA19: 
    ""
return 