label BwA18:
    "There was a competition stage situated in the heart of the Christmas market." 
    "Arriving at the competition stage, we suddenly realised that the area was quite empty." 
    u "I think that we're too late." 
    a "Huh?" 
    "I suddenly noticed a sign posted on the stage." 
    "\'Gift Wrapping competition concluded early as all prizes have been distributed.\'" 
    a "Aww..." 
    a "The competition really sounded fun." 
    u "Not really." 
    "It actually, it sounds {i}really{/i} lame." 
    a "I'm actually great at gift wrapping." 
    u "That's the {i}real{/i} reason you find it fun, huh." 
    a "Of course. If I can't win, what's the point?" 
    u "How competitive." 
    a "Well... then, what should we do now?" 
    u "Dunno." 
    "I noticed an empty bench near the stage." 
    u "Why don't we sit there at the bench?" 
    a "Why? It's not like I sprained my ankle while walking in sandals." 
    u "Who wears sandals in this weather?" 
    u "Regardless, you watch too many shows; you're thinking too deeply." 
    a "Why?" 
    a "Anime is fun to watch!" 
    u "Hehe." 
    a "What does that \'Hehe\' mean?" 
    a "Are you judging me?" 
    u "No, of course not. I, too, watch anime occasionally." 
    a "Then you have no grounds to judge me." 
    u "Didn't I just say that I wasn't judging you?" 
    a "Oh, right." 
    "The conversation up and died right there." 
    "How awkward..." 
    jump BwA19 
label BwA19: 
    "We both sat at the bench in an awkward silence." 
    a "There's a fireworks festival later." 
    u "Oh, I guess?" 
    u "There's nothing to pay for during some fireworks, right?" 
    u "So, can I go home?" 
    "[a] laughed." 
    a "Of course not, you dumbass." 
    u "Huh? But I need to do my holiday project." 
    a "Do you really not want a life?" 
    u "Of course not." 
    a "Do you not want to not have a life, or do you not want a life?" 
    u "I don't want a life." 
    a "You idiot." 
    "She covered her face is embarrassment, hitting me in the shoulder playfully." 
    "I really want to go home." 
    "The earlier incident aside, we sat in silence." 
    a "Remember the first time we met?" 
    u "The first time we met..." 
    "The first time we met was at the university's library last year during the summer hols." 
    "Being the time of year that it was, it was mostly empty." 
    "At the time, [a] suddenly came up to me while I was reading for research purposes and writing an essay on the side." 
    jump BwA20 
label BwA20: 
    a "What're you doing here?" 
    u "Is there anything that says I can't be here?" 
    u "I could return the question to you, if so." 
    a "Hmm... Good point." 
    "She sat down opposite me." 
    a "What're you reading?" 
    "I lifted up my book to reveal the cover." 
    "{i}The laws of thought{/i}, by George Boole"
    a "Ew, philosophy." 
    u "Huh?" 
    u "Is that how you speak to everyone?" 
    "How rude." 
    a "No, but you're a philosophy student." 
    "Then, could it be because she doesn't like humanities students?" 
    "She's pretty, but I never thought that she was a STEM student." 
    "Why would she be in an arts university if so, though?" 
    u "I'm also a math student, so..." 
    a "Eww." 
    "I can't understand what she's thinking." 
    u "What?" 
    a "Math is philosophy, right?" 
    u "More or less, but why do you hate philosophy students?" 
    a "I mean, if you're going to think about goodness or justice or knowledge, why don't you ecome a scientist or sociologist to learn more concrete facts?" 
    u "Don't compare me to those bastard axiologists, metaphysists and epistemologists." 
    u "I'm learning logic." 
    a "There are branches to philosophy?" 
    u "Of course." 
    a "Either way, logicians can't be good anyways." 
    a "You'll probably preach to me about good arguments and whatnot." 
    u "Huh..." 
    "This conversation's getting tiresome." 
    a "Har?! You picking a fight?" 
    u "No, I'm not picking a fight." 
    u "Either way, I can't understand how you got a challenge declaration from my 'huh'." 
    a "You can't undercstand because you're an idiot for studying philosophy." 
    u "Well, then, what do {i}you{/i} study?" 
    a "Acting, a much better degree than yours." 
    u "Oh, so you're a narcicist." 
    a "What did'ya just say?!" 
    "Needless to mention, we started off on the worng foot." 
    "Since then, she would come to the library every day just to insult me." 
    "I wasted my entire summer holidays because I couldn't study due to our diss wars." 
    jump BwA21
label BwA21: 
    u "Of course I remember." 
    a "Haha, do you remember how you called me every time we met?" 
    u "..." 
    u "Nope." 
    "I remember clearly." 
    "It was \'Supporting Cast\'." 
    "She got heated every time I called her that, and would constantly bug me to change it." 
    "Since she hated that form of address, it was only natural that I would continue to call her that." 
    a "Haha." 
    "She doesn't seem to believe me." 
    a "Is it so~?" 
    "She {i}definitely{/i} doesn't believe me." 
    u "Hehe." 
    u "So, what's your point?" 
    a "You know..." 
    a "We got quite close after insulting each other for a long time, right?" 
    u "You don't say?" 
    u "Who'd have thought that we would now be going on (platonic) Christmas dates?" 
    "[a] blushed." 
    a "Stop it." 
    u "You don't like me calling it that?" 
    a "Not really..." 
    u "Oh." 
    "Silence once again." 
    a "You know, I—"
    jump BwA22
label BwA22: 
    "She was interrupted by an announcement." 
    "Announcement" "The fireworks show is starting. Please do not approach the competition stage." 
    "[a] looked frustrated, but that was soon replaced by awe as a glowing trail snaked into the air."
    a "Beautiful." 
    u "Yes, very beautiful." 
    "I was just responding randomly because I was wondering what she was planinng to say just now." 
    "My eyes didn't leave her face even as I spoke, something that [a] seemed to vaguely notice." 
    "Coloured slightly red, [a] turned to face me." 
    "She took a deep breath." 
    a "You know, I really l-like you. Could you be my..." 
    "Her voice trailed off." 
    "She averted her gaze in embarrassment, staring at the competition stage." 
    "I got the gist of her words." 
    "Taking a deep breath, too, I started." 
    u "I—"
    scene bgblack with fade 
    $ renpy.movie_cutscene("mvcutscene.webm", delay=3, loops=0, stop_music=True)
    scene bgmov45 
    pause 5
    scene bgblack with fade 
    pause 10 
    jump BwA23 
label BwA23: 
    "During the Christmas festival, there was an accident." 
    "During the fireworks festival, a multi-shot firework abruptly tilted to the reaction force of the fireworks." 
    "The resulting explosion caused the death of three workers and a woman who was sitting at a nearby park bench." 
    "The man who was with the deceased woman was permanantly blinded in his right eye by the chemicals emitted." 
    "Based on eyewitness accounts, 18-year-old [a] was first to notice the firework's tilt, prompting her to jump in front of 18-year-old [u], saving his life at the sacrifice of hers." 
    "I listened to the news broadcasted on Christmas as I looked for [a]'s gravestone." 
    "Due to my injuries, I was unable to attend [a]'s funeral." 
    "On the day of my discharge, I directly headed to H City Xiaoshan Cemetary." 
    "Finally seeing the gravestone planted in the middle-class grave, my vision grew blurry." 
    "To the one who I never realised I loved until it was too late," 
    "goodbye." 
    scene bgblack with fade
    "Ending." 
    python: 
        if persistent.BwA23 == False: 
            persistent.BwA23 = True 
            persistent.gameState += 1 
    "Number of endings completed: [persistent.gameState]" 
menu:
    "What would you like to do now?" 
    "Quit": 
        return 
    "Try another path": 
        call start  
return 