label eAB10: 
    $ renpy.block_rollback()
    a "Drink? It's still 6 p.m." 
    u "Time's just a number." 
    "Spoken like a true university student, if I do say so myself." 
    a "Huh? What's that supposed to mean?" 
    a "If time's just a number, then the usual paedophile excuse, 'Age's just a number' is equally valid." 
    "I regret saying that now..." 
    u "Dunno." 
    "I really don't want to be here."
    "Maybe if I can get her blackout drunk, I can go home early." 
    "It's better than telling my mother that I ditched her." 
    a "Haha, do you want to get me drunk so that you can bring me to a hotel?" 
    "The first part, yes, but the second... not at all." 
    u "Not at all." 
    a "I guess we'll just buy something at the food district." 
    a "I'll get a non-alcoholic drink." 
    "Drat." 
    "The Christmas market was arranged into multiple different 'districts'." 
    "Each district contained a certain type of store." 
    "As implied by its name, the food district contained many food stalls." 
    u "A'ight." 
    "I mean, where else do we get drinks?" 
    "Are we supposed to walk to the nearest shopping mall and buy a beer from the local Vanguard?" 
    a "Yay, let's go!" 
    "She didn't seem to be hungry." 
    "Maybe she ate lunch later than usual." 
    "How irresponsible." 
    "That being said, I don't think I have the right to complain, since I suggested drinking on an empty stomach." 
    jump eAB11 

label eAB11: 
    a "I want to drink hot chocolate!" 
    u "Oh." 
    "How random." 
    "It's not like I need to know what she's drinking." 
    a "What about you?" 
    u "Gluhwein." 
    "There was a stall that sold it at the end of the district." 
    u "Glue-wine?" 
    u "What's that?" 
    u "German mulled wine." 
    a "Why're you drinking already?" 
    a "Didn't I say to get a non-alcoholic drink?" 
    "Since when did that apply to me?" 
    "I stared at her for a moment, after which [a] chose to give up." 
    a "Fine, you dumbass." 
    a "If you want to drink so much, why don't you just buy draught beers?" 
    a "They also have alcohol in them, and they're definitely much cheaper." 
    a "..." 
    a "Why're you looking at me with disdain?" 
    "The market did seem to sell draft beers, evidenced by a few barrels that were sitting at the back of a stall." 
    "But, I'm not someone who enjoys being drunk, but someone who likes the process of getting to that point." 
    "But seriously, I {i}do{/i} like mulled wine." 
    "My parents left some on the table unattended when I was a child." 
    "It smelt sweet, so I drank the entire mug." 
    "And being at that young age, I got blackout drunk with just that." 
    "After that..." 
    "Wait, I've digressed again." 
    "I liked how it tasted." 
    "It's sweet, unlike beer or whiskey etc." 
    a "Let's go buy whatever, then meet up in 10 minutes." 
    u "OK." 
    "No problem with that." 
    jump eAB12 

label eAB12: 
    a "Wait..." 
    "She paused suddenly." 
    a "We can't do that!" 
    a "The couple's discount!" 
    "Shit, I was hoping that she had forgotten about it." 
    u "{i}Sigh{/i}." 
    a "What does that sigh mean?" 
    a "Hey, don't ignore me!" 
    "I wasn't ignoring her, I'm just too lazy to explain anything." 
    "That comment escaped in the form of another sigh." 
    a "Oi, are you disregarding me, your {i}only{/i} friend now?" 
    a "Do you not consider me your friend?" 
    "She didn't have to emphasise that 'only' part." 
    "How annoying..." 
    u "No, I do." 
    a "Huh?" 
    u "Huh?" 
    "It's just three words." 
    "Is she so dumb that she was confused with just that?" 
    "As expected of an acting major (Pfft)." 
    a "Do you mean, you consider me as a friend, or do you not consider me as a friend?" 
    u "Option a), ma'am." 
    a "Ma'am? I'm the same age as you, young man." 
    "Are you bragging that you're mature for your age, or are you just mocking me?" 
    "Probably the latter." 
    u "Understood, ma'am." 
    "How annoying..." 
    "[a] chattered on and on as we went to a drink store advertising their 'World-famous' hot chocolate." 
    a "I want one cup, sir." 
    u "I don't." 
    "[a] glared at me." 
    "I guess, technically, I need not have said that." 
    "But I was annoyed with her constant chatter, so I wanted to annoy her too." 
    "Shopkeeper" "Alright, one cup of our specialty hot chocolate! 30 RMB!" 
    a "That's a scam!" 
    "Shopkeeper" "It clearly says that it's world-famous." 
    "Shopkeeper" "How can anything world-famous be cheap?" 
    a "Haha, then I'll just not buy it." 
    u "..." 
    "Shopkeeper" "..." 
    "It clearly says on the sign that it's 30 RMB per cup. Why're you even trying to bargain?" 
    u "Let's just leave." 
    a "Alright, how unreasonable." 
    "{i}You're{/i} the one who's unreasonable." 
    "I want to bury myself in a hole." 
    u "Shut up." 
    a "OK." 
    "Her stark attitude change from annoyed to meek was interesting." 
    "Her sudden attitude change from meek to excited was also interesting." 
    a "I'll try the glue-wine that you talked about!" 
    u "..." 
    "We went to a stall that sold gluhwein." 
    "We bought two large cups." 
    "The price was relatively reasonable, 14 RMB per large cup without the discount." 
    u "How's it?" 
    a "It's sweet." 
    "You don't say?" 
    a "I didn't expect wine to be sweet." 
    a "I thought it was always bitter." 
    a "Or sour." 
    u "..." 
    a "It really warms you up, huh?" 
    "Isn't that the reason mulled wine was created?" 
    a "Why're you so silent?" 
    u "..." 
    "Because... I don't have anything to say...?" 
    "What do you expect me to do?" 
    "Come up with meaningless topics like you normies?" 
    "I noticed that [a]'s face was slightly flushed." 
    "She didn't drink often, so her alcohol tolerance was low at best." 
    u "Drink slower." 
    a "Why?" 
    u "Drinking fast makes you drunk faster." 
    a "Oh... We can't have that." 
    "Instant regret." 
    "If she gets drunk, we can go home early." 
    a "You look like you're plotting to get me drunk." 
    u "No." 
    "'I wasn't plotting anything.'" 
    "'Trust me!'" 
    "Of course, I didn't say that aloud." 
    "Defending myself would probably make me more suspicious." 
    u "Shouldn't we move on?" 
    a "No rush, there's still a lot of time." 
    a "So, are you sure you weren't plotting anyone?" 
    u "If you want to be squeezed like a roll of toothpaste by the crowd later." 
    a "Haha, then we should really go." 
    u "..." 
    a "Where do you want to go?" 
    u "..." 
    "Home." 
    u "Dunno." 
    "I don't want to die, so I won't say that aloud." 
    a "Come on, just say something random!" 
    
    menu: 
        u "Erm..." 
        "Game district": 
            call sAB13 
        #TODO: BeAB13; 
return 