label sAB13: 
    $ renpy.block_rollback() 
    "Game district in the Christmas market." 
    a "What game do you want to play?" 
    u "...They're all the same (to me)."
    a "You... Geez, you're way too indifferent." 
    u "I'm not." 
    a "You are!" 
    u "Whatever." 
    u "You choose." 
    "The games seemed to all be lame." 
    "Wait, guessing the riddles?" 
    "Isn't that a Mid-autumn Festival game?" 
    u "How retarded." 
    a "What?" 
    u "There's a riddle guessing game here." 
    a "Oh, that's quite ironic." 
    "Neverthless, festivals are just excuses to have fun." 
    "Ultimately, it didn't matter what game is included, since all that matters is that everyone has fun." 
    "And everyone earns money, I guess." 
    a "Let's try it!" 
    "I fucking knew that she'd choose the most retarded option." 
    "Now, I can make fun of her, because guessing riddles is my advantage, whilst things requiring the brain is her disadvantage." 
    "Lady Boss" "Hi, beauty, handsome, do you want to guess some riddles?" 
    a "Yep!" 
    a "Are there any... prizes?" 
    "There wasn't anything that indicated that there was a reward." 
    "Lady Boss" "None, if you want, you can play the ball toss booth or something." 
    a "Oh." 
    a "Do we need to pay to play?" 
    "Lady Boss" "No need, "


return 