label sxA15: 
    "In the heart of the Christmas Market, there was a competition stage." 
    "On the competition stage was held a giftwrapping competition." 
    "Emcee" "Alright! Is there anyone else who wants to come up?!" 
    "Emcee" "The current record is 20.3 seconds by Mister Lu Hua!" 
    a "Wow, so fast!" 
    u "..." 
    "To be honest, I wasn't very interested." 
    "According to a screen by the side of the stage, the top ten fastest gift wrappers would get vouchers." 
    "The top three would get vouchers and a medal." 
    "The champion gets vouchers and a 'secret gift', whatever that was." 
    "The tenth place had a time of 25.8 seconds." 
    a "Why don't we participate?" 
    u "I don't really want to, though." 
    a "...Alright, then." 
    "She walks up onto the stage." 
    "Emcee" "We have a new competitor!" 
    "Emcee" "What's your name, little miss?" 
    a "Hehe, hi, I'm [a]." 
    a "I'm honoured to come to a competition like this!" 
    "Emcee" "Alright, let's start." 
    "Emcee" "Do you know what you need to do in this competition?" 
    a "We wrap a present, right?" 
    "There was a sound of laughter." 
    "Emcee" "Of course we must wrap a present!" 
    "Emcee" "You must wrap that box over there with the wrapping paper and tape provided." 
    "[a] walked to the table where the tape and wrapping paper lay." 
    "Emcee" "Are you ready?!" 
    a "Yes!" 
    "Emcee" "Then you may start in 3...{w=1} 2...{w=1} 1...{w=1} you may start now!" 
    "[a] hastily attempts to wrap the tape."
    "She manages to completely wrap the present in 22.6 seconds." 
    "Emcee" "Aww, such a shame. You couldn't beat Mr. Lu's record." 
    "Emcee" "But now, you're the new 6th place!" 
    "Emcee" "So... You get a 150 RMB voucher at XX bookstore!" 
    a "Yay!" 
    jump sxA16 

label sxA16: 
    "[a] jumps off the competition stage, walking up to me." 
    a "Did you see?" 
    u "See what?" 
    "She knocked me lightly on my head." 
    a "I wrapped it in 22.6 seconds." 
    u "I know." 
    a "Hmph." 
    "What the hell's wrong with her?" 
    "She seemed to be in a bad mood." 
    "But her bad mood didn't last for very long." 
    a "Isn't there a game district? Let's go." 
    u "Alright." 
    jump sxA17 

label sxA17: 
    "There was a game district in the market." 
    "We headed to the game district." 
    a "What game do you mant to play?" 
    u "No clue. What do you want?" 
    a "I want to play... Oh, a shiba inu plushy..." 
    a "I want it!" 
    u "Oh, OK." 
    "We went to the stall that hung up the shiba inu toy." 
    "Shopkeeper" "Do you want to play?" 
    a "Yup!" 
    "Shopkeeper" "Then, how many balls do you want?" 
    a "How many do you think we need to win it?" 
    u "Dunno. Maybe 5 for now." 
    "Shopkeeper" "Then, that'll be 25 RMB." 
    u "Oh." 
    "Shopkeeper" "Are you a couple?" 
    u "Yes..." 
    "I'm still not used to calling [a] my girlfriend." 
    "Not that we're a couple, anyways." 
    "The shopkeeper seemed unconvinced." 
    "Shopkeeper" "Then, prove it." 
    a "Uhm.. Alright." 
    "I felt a soft feeling on my cheek." 
    $ renpy.music.set_pause(True, channel="music") 
    "The world seemed to stop." 
    "After a moment, I finally understood what happened." 
    $ renpy.music.set_pause(False, channel="music") 
    "Flushing red, I glared at her." 
    "Her face was entirely red." 
    "The store owner guffawed." 
    "Shopkeeper" "I was just kidding." 
    u "Oh." 
    "Then why didn't you say that before she kissed me?" 
    "Then again, she acted so quickly that it was unreasonable to expect him to react on time." 
    "The owner handed over 2.5 RMB along with 6 balls." 
    "Shopkeeper" "One free for putting on such a good show." 
    "We both reddened after being reminded of the incident." 
    a "Oh..." 
    u "Uhm... shall we... try to win the shiba inu?" 
    a "Alright..." 
    a "Three and three, right?" 
    a "The balls, I mean." 
    u "That's fine." 
    a "Alright, shiba inu, I'm coming for you!" 
    



return 