label sxA20: 
    "We sat at a bench in the park." 
    "It was much quieter compared to the bustle of the Christmas market." 
    a "Right,{w=.1} eggnog!" 
    "Her sudden exclaimation shocked me." 
    u "Oh...{w=.3} you finally remembered?" 
    "She really is an airhead." 
    a "Yep,{w=.1} can you help me buy it?" 
    a "Please?" 
    u "What about the couple's discount?" 
    a "Lazy.{w=.3} Also,{w=.1} I can't buy anything while holding doge." 
    "Doge was probably the name she gave to the plushie." 
    u "Alright..." 
    "I reluctantly returned to the food section,{w=.1} bought two cups of eggnog,{w=.1} then headed towards the park." 
    "There seemed to be some kind of ruckus in the park." 
    jump sxA21 

label sxA21: 
    "I quickened my footsteps while trying not to spill the eggnog." 
    "At the bench was [a] and another man." 
    "Man" "Why don't you come along with me?" 
    a "No,{w=.1} don't want to." 
    "Man" "Why not? Are you on a date?" 
    "Man" "Why don't you dump him and come with me?" 
    a "I'm not on a date." 
    "She seemed to be very annoyed." 
    "Man" "Then there's no problem,{w=.1} right?" 
    a "There's definitely a problem,{w=.1} and that's that I don't want to go with you." 
    "Man" "Why not?" 
    "Man" "Come on,{w=.1} I'll show you something much better than your friend can." 
    "The man grabbed onto her arm,{w=.1} pulling her with some strength." 
    a "Stop! Erm...{w=.3} Uhm...{w=.3} Help!" 
    "How amusing;{w=.2} she was so flustered she forgot how to say 'help'." 
    "Wait,{w=.1} that's not the point here." 
    "Finally,{w=.1} I have grounds to claim self-defense." 
    u "A'ight,{w=.1} that's enough." 
    "Since his attention was completely on [a],{w=.1} his back was completely open." 
    "I kicked him diagonally in the ass,{w=.1} so that he fell onto the bench,{w=.1} then dumped a cup of piping hot eggnog onto his face." 
    "Man" "What the fuck— Fuck you!" 
    "I held onto [a]'s hand,{w=.1} poured the other cup of eggnog onto his crotch (Since I can't run while holding it anyways),{w=.1} then ran away,{w=.1} pulling [a] along." 
    a "Finally,{w=.1} you acted." 
    "She probably saw me while I was waiting for an excuse to kick him." 
    u "Sorry,{w=.1} the eggnog..." 
    a "No need,{w=.1} at least I still have doge." 
    u "..." 
    u "Well,{w=.1} let's go somewhere with more people." 
    a "Haha!" 
    u "Why're you laughing?" 
    u "Well,{w=.1} it's fun." 
    "My face turned gloomy." 
    u "Then I want to see whatever you don't think is fun." 
    u "It must be like...{w=.3} hell,{w=.1} or something." 
    a "Hehe!" 
    "We returned to the game district,{w=.1} which was the closest area to us." 
    a "The fireworks show should happen in 5 minutes or so." 
    u "And?" 
    a "Dunno,{w=.1} just wanted to say it."    
    u "Oh." 
    jump sxA22 

label sxA22: 
    "Soon,{w=.1} there was an announcement over the intercom system." 
    "Announcer" "The fireworks show is starting.{w=.3} For safety reasons,{w=.1} please do not approach the competition stage." 
    "Soon,{w=.1} there was a whistling sound as a glowing trail headed towards the heavens,{w=.1} followed by multiple others." 
    "Immediately after,{w=.1} the fireworks exploded into a flower of sparks." 
    "This was actually my first time seeing fireworks in person." 
    "It looks much better than it does on TV." 
    a "Wow,{w=.1} so beautiful!" 
    u "Yep,{w=.1} it's quite beautiful." 
    a "Wait,{w=.1} why don't we record it?" 
    a "I want to share it on my lecture group chat." 
    u "Good point." 
    "I took out my phone." 
    "The voice recorder was still on." 
    "I started the audio recording when that bastard tried to screw with [a]." 
    "Just in case I need to submit it as evidence if he tried to sue us afterwards." 
    "I stopped the recording,{w=.1} then opened the camera app,{w=.1} recording the fireworks." 
    a "You should watch the fireworks too,{w=.1} you know?" 
    a "Don't just look at it through the screen." 
    a "You can't get the full experience like that." 
    u "Oh." 
    "The fireworks really were beautiful." 
    jump sxA23 

label sxA23: 
    "After the fireworks show,{w=.1} the crowds dispersed and the stalls closed up for the day." 
    u "Should I walk you home?" 
    u "It's really quite late." 
    a "Alright." 
    "I walked her home." 
    "Her house was a little closer to the market than mine." 
    "We exchanged some banter along the way." 
    "Finally,{w=.1} we arrived at her apartment." 
    "Standing in the fluorescent lightning of the apartment hallway,{w=.1} [a] turned around." 
    a "I had quite a lot of fun today." 
    u "Me too." 
    a "I hope that we can do this next year,{w=.1} too."   
    u "Same." 
    "What she said was quite strange since we both have 2 more years in university,{w=.1} but I didn't think much of it." 
    a "Then,{w=.1} goodbye." 
    u "Goodbye." 
    "Ending." 
    "Path taken: A,{w=.1} A,{w=.1} A,{w=.1} A,{w=.1} A,{w=.1} A." 
    $ cmpltd_sxA23 = True 
    $ gamestate += 1 
    "Endings completed: [gamestate]."
return 