label wA13: 
    u "I want to eat roast beef sandwich." 
    a "Huh, that sounds great." 
    a "I'll try it, too!"
    "We walk up to the stall."
    "Shopkeeper A" "Hey, do you want to try some roast beef? I have some samples!" 
    "He reveals a plate with multiple pieces of roast beef impaled by toothpicks." 
    "Without hesitation, [a] picks one up and tries it." 
    a "Wow, this is great." 
    a "Honey, I want to eat this." 
    u "..." 
    "I was completely thrown off-guard." 
    "I completely forgot about the bullshit with the couple's discount." 
    "Shopkeeper A" "You're dating? Then I'll give you a 10% discount." 
    u "Alright, umm..." 
    u "Then, get me 4 pieces." 
    "Shopkeeper A" "A'ight, 28 RMB." 
    "The sale price of the sandwich is 30 RMB." 
    u "Do you think I can't do basic math?" 
    u "90% of 30 is 27." 
    "Shopkeeper A" "Alright, I'll make a loss and sell it for 27." 
    "I'm speechless." 
    "How can anyone be so shameless?" 
    jump wA14 

label wA14: 
    "We sat down by a side with food." 
    a "Ahh, how warm!" 
    "She squeezed on the sandwich like it was a hand warmer." 
    u "..." 
    u "Just eat it." 
    a "Don't wanna, we ran out of hand warmers at home!" 
    u "So?" 
    a "So, I'm cold!" 
    u "Then bear with it."